# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the contents of the frontend directory to the Nginx default public directory
COPY . /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80
